### ISSUE TITLE
My touchpad issue has been resolved

### ISSUE THREAD

**Issue by ClefairyBlame** [ehinium/Asus-ROG-Strix-G15-G512LV-OpenCore#3]
My touchpad issue has been resolved

**Comment by ghost** [comment]
Good! Could you explain to me how to fix it?

**Comment by ClefairyBlame** [comment]
[SSDT-ETPX.aml.zip](https://github.com/ehinium/Asus-ROG-Strix-G15-G512LV-OpenCore/files/5472652/SSDT-ETPX.aml.zip)
Used the SSDT,and VoodooI2C.kext、VoodooI2CHID.kext

**Comment by ghost** [comment]
Thank you!
