### ISSUE TITLE
About terrible battery life

### ISSUE THREAD

**Issue by ClefairyBlame** [ehinium/Asus-ROG-Strix-G15-G512LV-OpenCore#5]
I think this is caused by not completely disabling the GPU

**Comment by ClefairyBlame** [comment]
[https://dortania.github.io/OpenCore-Install-Guide/extras/spoof.html#ssdt-method](url)
Try SSDT method

**Comment by ghost** [comment]
I did try this, but it didn't work. I guess this is an issue with CPU or maybe wrong CpuFriend and SMBIOS (Currently macbookpro16,4). Because CPU temperature is always above 60 degrees Celcius which isn't normal, maybe changing SMBIOS could fix it. I will work on it.

**Comment by koluris** [comment]
This might be true, please check last commit solution on this repo: https://github.com/dkoluris/ZEPHYRUS-M15-GU502-OpenCore

**Comment by ehinium** [comment]
> This might be true, please check last commit solution on this repo: https://github.com/dkoluris/ZEPHYRUS-M15-GU502-OpenCore

Yes that's right, It worked thank you.
