### ISSUE TITLE
kp on VoodooGPIO after bios 311

### ISSUE THREAD

**Issue by Gwinilts** [ehinium/Asus-ROG-Strix-G15-G512LV-OpenCore#6]
Hi,

Unfortunately I updated bios after getting this laptop, thinking bios may be culprit. VoodooGPIO is causing a kernel panic as soon as it loads. Disabling it in opencore prevents KP but also means touchpad will not work.

Disabling SSDT-ETPX also prevents KP but means touchpad will not work.

I tried to ascertain value for GPIO pin and got 0x6c instead of 0x8c (maybe my bad baths), still KP
Will try other values for pin

Do you have any advice? My advice is don't update BIOS

**Comment by ehinium** [comment]
Hi, sorry for replying so late. I have updated my bios several times since I started using Hackintosh (now I'm on v312), but I haven't had any issues so far. I just updated my EFI; if you are still having the issue, you can try it.

**Comment by Gwinilts** [comment]
Hi

I fixed the issue by removing some unnecessary code from GPIO acpi, i will
send you the reduced dsl file, it will be more compatible
