### ISSUE TITLE
The Version of 10875h could be blurred screen

### ISSUE THREAD

**Issue by ODINSHAN** [ehinium/Asus-ROG-Strix-G15-G512LV-OpenCore#7]
I tried to update the oc version to the latest version, and changed the id of the counterfeit nuclear display. Well, I tried to fix the occasional splash screen caused by the high refresh rate, but it didn't work. I will continue to try.  This is the configuration file I modified based on your configuration file. I hope you can give me some guidance.
link：https://drive.google.com/file/d/1JaGC4j8TssEyoSoMAjBaZrPD10xiExXq/view?usp=sharing

**Comment by ODINSHAN** [comment]
OC version is 0.6.8

**Comment by ehinium** [comment]
Hi, your question is a little unclear to me. If you are still having the problem, please explain it in more detail.

**Comment by ODINSHAN** [comment]
Thank you for your reply. I have successfully solved the 240Hz version of g512lv screen flicker problem, it is caused by backlight recognition failure, and I inquired about the screen output mode, to maximize its transmission rate definition, now it is normal, thank you!I just made some changes in your config file to make it adapt to the 240Hz screen of g512lv.Thank you very much for your DSDT file！

> <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
	<dict>
		<key>AAPL,GfxYTile</key>
		<data>
		AQAAAA==
		</data>
		<key>AAPL,ig-platform-id</key>
		<data>
		CQCbPg==
		</data>
		<key>device-id</key>
		<data>
		mz4AAA==
		</data>
		<key>enable-backlight-registers-fix</key>
		<data>
		AQAAAA==
		</data>
		<key>enable-hdmi-dividers-fix</key>
		<data>
		AQAAAA==
		</data>
		<key>force-online</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con1-busid</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con1-enable</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-con1-type</key>
		<data>
		AAgAAA==
		</data>
		<key>framebuffer-fbmem</key>
		<data>
		AACQAA==
		</data>
		<key>framebuffer-patch-enable</key>
		<data>
		AQAAAA==
		</data>
		<key>framebuffer-stolenmem</key>
		<data>
		AAAwAQ==
		</data>
		<key>hda-gfx</key>
		<string>onboard-1</string>
		<key>model</key>
		<string>Intel UHD Graphics</string>
	</dict>
</dict>
</plist>

**Comment by ehinium** [comment]
> Thank you for your reply. I have successfully solved the 240Hz version of g512lv screen flicker problem, it is caused by backlight recognition failure, and I inquired about the screen output mode, to maximize its transmission rate definition, now it is normal, thank you!I just made some changes in your config file to make it adapt to the 240Hz screen of g512lv.Thank you very much for your DSDT file！
> 
> > 
> 
> PciRoot(0x0)/Pci(0x2,0x0) AAPL,GfxYTile AQAAAA== AAPL,ig-platform-id CQCbPg== device-id mz4AAA== enable-backlight-registers-fix AQAAAA== enable-hdmi-dividers-fix AQAAAA== force-online AQAAAA== framebuffer-con1-busid AQAAAA== framebuffer-con1-enable AQAAAA== framebuffer-con1-type AAgAAA== framebuffer-fbmem AACQAA== framebuffer-patch-enable AQAAAA== framebuffer-stolenmem AAAwAQ== hda-gfx onboard-1 model Intel UHD Graphics

Your welcome! Good to hear that.
